#!/usr/bin/env php
<?php
require realpath('.') . "/vendor/autoload.php";

use Profiler\Profiler;
use Symfony\Component\Dotenv\Dotenv;

(new Dotenv())->load(__DIR__ . '/.env');
(new Profiler())->run();
